#ifndef EMERGENCYCENTER_GLOBAL_H
#define EMERGENCYCENTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EMERGENCYCENTER_LIBRARY)
#  define EMERGENCYCENTER_EXPORT Q_DECL_EXPORT
#else
#  define EMERGENCYCENTER_EXPORT Q_DECL_IMPORT
#endif

#endif // EMERGENCYCENTER_GLOBAL_H
